const {
  MONGO_HOST,
  MONGO_PORT,
  MONGO_DB,
  MONGO_SSL,
  MONGO_USER,
  MONGO_PASS,
  DISABLE_CORS,
} = process.env;

const DEFAULT_MONGO_HOST = 'ds145289.mlab.com';
const DEFAULT_MONGO_PORT = '45289';
const DEFAULT_MONGO_DB = 'stmapp';
const DEFAULT_MONGO_SSL = false;
const DEFAULT_MONGO_USER = 'admin';
const DEFAULT_MONGO_PASS = 'admin';

const DEFAULT_DISABLE_CORS = false;

export const CONFIG = {
  MONGO_HOST: MONGO_HOST || DEFAULT_MONGO_HOST,
  MONGO_PORT: MONGO_PORT || DEFAULT_MONGO_PORT,
  MONGO_DB: MONGO_DB || DEFAULT_MONGO_DB,
  MONGO_SSL: MONGO_SSL || DEFAULT_MONGO_SSL,
  MONGO_USER: MONGO_USER || DEFAULT_MONGO_USER,
  MONGO_PASS: MONGO_PASS || DEFAULT_MONGO_PASS,
  DISABLE_CORS: DISABLE_CORS || DEFAULT_DISABLE_CORS,
};
